import { Metadata } from "next";
import { AlertTriangle, Calculator, Shield, ExternalLink, FileText, Lock } from "lucide-react";

export const metadata: Metadata = {
  title: "Disclaimer - TakeTheTools",
  description:
    "Read the TakeTheTools disclaimer. Our tools are for informational and educational purposes only. Results should not be used as professional advice.",
  alternates: {
    canonical: "https://takethetools.com/disclaimer",
  },
};

export default function DisclaimerPage() {
  const sections = [
    {
      icon: Calculator,
      title: "Financial & Calculator Tools",
      content:
        "All financial calculators on TakeTheTools — including loan calculators, percentage calculators, compound interest tools, and any other financial tools — are provided for informational and educational purposes only. Results generated by these tools do not constitute financial advice, tax advice, or investment recommendations. Always consult a qualified financial advisor before making any financial decisions.",
    },
    {
      icon: Shield,
      title: "Health & BMI Tools",
      content:
        "Health-related tools such as BMI calculators, calorie calculators, and body measurement tools are intended for general informational purposes only. Results are not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.",
    },
    {
      icon: Lock,
      title: "Security & Encryption Tools",
      content:
        "Encryption, hashing, and security tools provided on TakeTheTools are meant for educational and development purposes only. We do not guarantee that any encryption or hashing method is suitable for securing sensitive or classified data in a production environment. Do not use these tools to encrypt confidential personal, financial, or government data without consulting a security professional.",
    },
    {
      icon: FileText,
      title: "General Tool Results",
      content:
        "All tools on TakeTheTools are provided on an 'as is' and 'as available' basis. While we strive for accuracy, we do not warrant that the results produced by any tool are complete, accurate, or error-free. You use the results at your own risk. TakeTheTools is not liable for any decisions made based on tool outputs.",
    },
    {
      icon: ExternalLink,
      title: "External Links",
      content:
        "Our website may contain links to third-party websites or resources. These links are provided for your convenience and informational purposes only. TakeTheTools does not endorse, control, or take responsibility for the content, privacy policies, or practices of any third-party websites. We encourage you to review the terms and privacy policies of any third-party sites you visit.",
    },
    {
      icon: AlertTriangle,
      title: "No Professional Relationship",
      content:
        "Use of TakeTheTools does not create any professional, client, or advisory relationship between you and TakeTheTools. The content and tools provided on this website are not a substitute for professional advice from a licensed attorney, financial advisor, medical doctor, or any other qualified professional.",
    },
  ];

  return (
    <div className="pt-10 pb-20">
      <div className="container mx-auto px-4 max-w-4xl">

        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-amber-50 rounded-2xl mb-6">
            <AlertTriangle className="w-8 h-8 text-amber-500" />
          </div>
          <h1 className="text-4xl md:text-6xl font-display font-bold text-slate-900 mb-6 tracking-tight">
            Dis<span className="text-primary-600">claimer</span>
          </h1>
          <p className="text-xl text-slate-600 leading-relaxed max-w-2xl mx-auto">
            Please read this disclaimer carefully before using any tools on
            TakeTheTools. By using our tools, you agree to the terms outlined
            below.
          </p>
          <p className="text-sm text-slate-400 mt-4">
            Last Updated: May 10, 2026
          </p>
        </div>

        {/* General Disclaimer Box */}
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 mb-12">
          <div className="flex gap-4 items-start">
            <AlertTriangle className="w-6 h-6 text-amber-500 mt-1 shrink-0" />
            <div>
              <h2 className="text-lg font-bold text-amber-800 mb-2">
                General Disclaimer
              </h2>
              <p className="text-amber-700 leading-relaxed text-sm">
                The information, tools, and results provided on{" "}
                <strong>takethetools.com</strong> are for{" "}
                <strong>general informational and educational purposes only</strong>.
                Nothing on this website constitutes professional advice of any
                kind. TakeTheTools makes no guarantees regarding the accuracy,
                completeness, or suitability of any tool or its results for any
                particular purpose.
              </p>
            </div>
          </div>
        </div>

        {/* Section Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
          {sections.map((section, index) => (
            <div
              key={index}
              className="p-6 bg-white rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-all duration-300"
            >
              <div className="w-11 h-11 bg-primary-50 rounded-xl flex items-center justify-center text-primary-600 mb-4">
                <section.icon className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-bold text-slate-900 mb-3">
                {section.title}
              </h3>
              <p className="text-slate-500 leading-relaxed text-sm">
                {section.content}
              </p>
            </div>
          ))}
        </div>

        {/* Limitation of Liability */}
        <div className="bg-slate-50 rounded-2xl border border-slate-100 p-8 mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-4">
            Limitation of Liability
          </h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            To the fullest extent permitted by applicable law, TakeTheTools and
            its operators shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages — including but not
            limited to loss of data, loss of profits, or business interruption
            — arising from your use of or inability to use the Site or its
            tools, even if TakeTheTools has been advised of the possibility of
            such damages.
          </p>
          <p className="text-slate-600 leading-relaxed">
            Your use of any tool on this Site is entirely at your own risk.
            TakeTheTools provides tools on an <strong>&quot;as is&quot;</strong> basis
            without warranties of any kind, either express or implied.
          </p>
        </div>

        {/* Accuracy */}
        <div className="bg-slate-50 rounded-2xl border border-slate-100 p-8 mb-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-4">
            Accuracy of Information
          </h2>
          <p className="text-slate-600 leading-relaxed">
            While we make every effort to ensure our tools produce accurate
            results, we cannot guarantee that all outputs are free from errors.
            Tool results may be affected by user input errors, browser
            compatibility issues, or changes in underlying data or formulas. We
            reserve the right to update, modify, or remove any tool at any time
            without prior notice.
          </p>
        </div>

        {/* Changes */}
        <div className="bg-slate-50 rounded-2xl border border-slate-100 p-8 mb-12">
          <h2 className="text-2xl font-bold text-slate-900 mb-4">
            Changes to This Disclaimer
          </h2>
          <p className="text-slate-600 leading-relaxed">
            We reserve the right to update or modify this Disclaimer at any
            time. Changes will be effective immediately upon posting to the
            Site. Your continued use of TakeTheTools after any changes
            constitutes your acceptance of the updated Disclaimer. We encourage
            you to review this page periodically.
          </p>
        </div>

        {/* Contact */}
        <div className="text-center bg-primary-50 rounded-2xl border border-primary-100 p-8">
          <h2 className="text-xl font-bold text-slate-900 mb-3">
            Questions About This Disclaimer?
          </h2>
          <p className="text-slate-600 mb-4">
            If you have any questions or concerns about this Disclaimer, please
            contact us.
          </p>
          <a
            href="mailto:support@takethetools.com"
            className="inline-flex items-center gap-2 px-6 py-3 bg-primary-600 text-white font-semibold rounded-xl hover:bg-primary-700 transition-colors"
          >
            <ExternalLink className="w-4 h-4" />
            support@takethetools.com
          </a>
        </div>

      </div>
    </div>
  );
}